# ------------------- SERVICE ------------------- #
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: ${APP_NAME}
    stage: ${STAGE}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9030
    - name: https
      port: 443
      targetPort: 9030
  type: NodePort
  selector:
    app: ${APP_NAME}

---
# ------------------- HPA ------------------- #
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${APP_NAME}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

---
# ------------------- SERVICE ACCOUNT ------------------- #
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${STAGE}-eks-${APP_NAME}"
  labels:
    app.kubernetes.io/name: ${APP_NAME}
  name: ${APP_NAME}

---
# ------------------- CLUSTER ROLE BINDING ------------------- #

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ${APP_NAME}-fluentd-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd-spring
subjects:
  - kind: ServiceAccount
    name: ${APP_NAME}
    namespace: ${STAGE}

---
# ------------------- DEPLOYMENT ------------------- #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  revisionHistoryLimit: 14
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: ${APP_NAME}
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: Build ${BUILD_SHA}
      labels:
        app: ${APP_NAME}
    spec:
      serviceAccountName: ${APP_NAME}
      volumes:
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: app-logs
          emptyDir: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - image: ${IMAGE_TAG}
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/log/containers
              name: app-logs
          name: ${APP_NAME}
          livenessProbe:
            httpGet:
              path: /${APP_NAME}/actuator/health
              port: 9030
            initialDelaySeconds: 50
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /${APP_NAME}/actuator/health
              port: 9030
            initialDelaySeconds: 50
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 60
          resources:
            requests:
              cpu: ${APP_RESOURCES_CPU_REQUEST}
              memory: ${APP_RESOURCES_MEMORY_REQUEST}
            limits:
              memory: ${APP_RESOURCES_MEMORY_LIMIT}
          ports:
            - containerPort: 9030
              protocol: TCP
          env:
            - name: ENV
              value: ${STAGE}
            - name: PROFILES_LABEL
              value: ${STAGE}
            - name: BUILD_HASH
              value: ${BUILD_SHA}
            - name: TREND_AP_KEY
              valueFrom:
                secretKeyRef:
                  name: trend-micron
                  key: key-spin-backend-services
            - name: TREND_AP_SECRET
              valueFrom:
                secretKeyRef:
                  name: trend-micron
                  key: secret-spin-backend-services
            - name: PAGOPOP_SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pagopop
                  key: pagopop-service-api-key
            - name: PAGOPOP_SERVICE_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: pagopop
                  key: pagopop-service-admin-api-key
            - name: AWS_COGNITO_JWKS
              valueFrom:
                secretKeyRef:
                  name: pagopop
                  key: aws-cognito-jwks
            - name: MONGODB_READ_PREFERENCE
              valueFrom:
                secretKeyRef:
                  name: pagopop
                  key: mongodb-read-preference
                  optional: true
            - name: MONGODB_URI_SECURITY
              valueFrom:
                secretKeyRef:
                  name: security-service
                  key: mongodb-security-uri
            - name: RENOVATION_HOURS
              valueFrom:
                secretKeyRef:
                  name: security-service
                  key: renovation-hours
            - name: EXPIRATION_HOURS
              valueFrom:
                secretKeyRef:
                  name: security-service
                  key: expiration-hours
            - name: TOKEN_BYTES
              valueFrom:
                secretKeyRef:
                  name: security-service
                  key: token-bytes
            - name: VOLTAGE_CREDENTIAL_POLICY_URL
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-credential-policy-url
            - name: VOLTAGE_CREDENTIAL_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-credential-identity
            - name: VOLTAGE_CREDENTIAL_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-credential-shared-secret
            - name: VOLTAGE_CREDENTIAL_FORMAT
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-credential-format
            - name: VOLTAGE_DATA_POLICY_URL
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-data-policy-url
            - name: VOLTAGE_DATA_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-data-identity
            - name: VOLTAGE_DATA_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-data-shared-secret
            - name: VOLTAGE_DATA_FORMAT
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-data-format
            - name: VOLTAGE_INTEGRITY_ACTIVATION_POLICY_URL
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-activation-policy-url
            - name: VOLTAGE_INTEGRITY_ACTIVATION_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-activation-identity
            - name: VOLTAGE_INTEGRITY_ACTIVATION_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-activation-shared-secret
            - name: VOLTAGE_INTEGRITY_ACTIVATION_FORMAT
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-activation-format
            - name: VOLTAGE_INTEGRITY_DEPOSIT_POLICY_URL
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-deposit-policy-url
            - name: VOLTAGE_INTEGRITY_DEPOSIT_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-deposit-identity
            - name: VOLTAGE_INTEGRITY_DEPOSIT_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-deposit-shared-secret
            - name: VOLTAGE_INTEGRITY_DEPOSIT_FORMAT
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-deposit-format
            - name: VOLTAGE_INTEGRITY_WITHDRAWAL_POLICY_URL
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-withdrawal-policy-url
            - name: VOLTAGE_INTEGRITY_WITHDRAWAL_IDENTITY
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-withdrawal-identity
            - name: VOLTAGE_INTEGRITY_WITHDRAWAL_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-withdrawal-shared-secret
            - name: VOLTAGE_INTEGRITY_WITHDRAWAL_FORMAT
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-integrity-withdrawal-format
            - name: VOLTAGE_PRODUCT_NAME
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-product-name
            - name: VOLTAGE_PRODUCT_VERSION
              valueFrom:
                secretKeyRef:
                  name: voltage
                  key: voltage-product-version
            - name: FEATURE_CONFIGCAT_APIKEY
              valueFrom:
                secretKeyRef:
                  name: feature-flags
                  key: configcat-apikey
            - name: FEATURE_CONFIGCAT_ENABLED
              valueFrom:
                secretKeyRef:
                  name: feature-flags
                  key: configcat-enabled
            - name: FEATURE_CONFIGCAT_MEMORY_MAP
              valueFrom:
                secretKeyRef:
                  name: feature-flags
                  key: configcat-memory-map
                  optional: true
            - name: SPRING_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-host
            - name: SPRING_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-port
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: pagopop
                  key: aws-region
        - name: logrotate
          image: ${LOGROTATE_IMAGE}
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: ${LOGROTATE_RESOURCES_CPU_REQUEST}
              memory: ${LOGROTATE_RESOURCES_MEMORY_REQUEST}
            limits:
              cpu: ${LOGROTATE_RESOURCES_CPU_LIMIT}
              memory: ${LOGROTATE_RESOURCES_MEMORY_LIMIT}            
          volumeMounts:
            - mountPath: /var/log/containers
              name: app-logs
          env:
            - name: CRON_EXPR
              value: "*/15 * * * *"
            - name: LOGROTATE_LOGFILES
              value: "/var/log/containers/*.log"
            - name: LOGROTATE_FILESIZE
              value: "50M"
            - name: LOGROTATE_FILENUM
              value: "5"
        - name: fluent-bit
          image: ${FLUENT_BIT_IMAGE}
          securityContext:
            runAsUser: 0
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: pagopop
                  key: aws-region
            - name: CLUSTER_NAME
              value: ${STAGE}-eks-master-cluster
            - name: HTTP_SERVER
              value: "On"
            - name: HTTP_PORT
              value: "2020"
            - name: READ_FROM_HEAD
              value: "true"
            - name: READ_FROM_TAIL
              value: "true"
            - name: APP_NAME
              value: ${APP_NAME}
            - name: STAGE
              value: ${STAGE}
            - name: CI_VERSION
              value: "k8s/1.3.9"
          resources:
            limits:
              cpu: ${FLUENT_BIT_RESOURCES_CPU_LIMIT}
              memory: ${FLUENT_BIT_RESOURCES_MEMORY_LIMIT}
            requests:
              cpu: ${FLUENT_BIT_RESOURCES_CPU_REQUEST}
              memory: ${FLUENT_BIT_RESOURCES_MEMORY_REQUEST}
          volumeMounts:
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/
            - name: app-logs
              mountPath: /var/log/containers

