name: Selective deploy

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  defaults:
    outputs:
      services: ${{ toJson(github.event.client_payload.services) || steps.main.outputs.services }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        if: '!github.event.client_payload.services'
        with:
          ref: ${{ github.event.client_payload.branch }}
      - id: main
        env:
          SERVICES_JSON: '${{ toJson(github.event.client_payload.services) }}'
          VALIDATE_PAYLOAD_SERVICES_JQ_SCRIPT: |
            env.SERVICES_JSON |
            (try fromjson | arrays | select(length > 0)) // error(
              "services should be a json list of projects from settings.gradle. Got: \(.)")

          LOAD_DEFAULT_SERVICES_AWK_SCRIPT: |
            BEGIN {FS="'"}         # subproject names are surrounded by single quotes
            $1 !~ "include" {next} # subprojects are denoted by include command
            $2 == "core"    {next} # core subproject is a library, not a microservice, skip.
            {print $2}

        run: |
          printf %s '::set-output name=services::'
          if test -z '${{ github.event.client_payload.services }}'; then
            awk "$LOAD_DEFAULT_SERVICES_AWK_SCRIPT" README.md | jq -MncR '[inputs]'
          else
            jq -Mnc "$VALIDATE_PAYLOAD_SERVICES_JQ_SCRIPT"
          fi

  build:
    needs: defaults
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.defaults.outputs.services) }}

    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.app_name }} done
          echo ${{ github.event.client_payload.branch }} branch
          echo ${{ github.event.client_payload.env }} env
