name: Selective deploy

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  defaults:
    outputs:
      services: ${{ toJson(github.event.client_payload.services) || steps.main.outputs.services }}
    runs-on: ubuntu-latest
    steps:
      - env:
          SERVICES: ${{ toJson(github.event.client_payload.services) }}
        run: |
          echo "$SERVICES"
      - uses: actions/checkout@v2
        if: '!github.event.client_payload.services'
        with:
          ref: ${{ github.event.client_payload.branch }}
      - id: main
        if: '!github.event.client_payload.services'
        run: |
          printf %s '::set-output name=services::'
          jq -cnR '[inputs]' README.md
  build:
    needs: defaults
    strategy:
      matrix:
        app_name: ${{ fromJson(needs.defaults.outputs.services) }}

    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.app_name }} done
          echo ${{ github.event.client_payload.branch }} branch
          echo ${{ github.event.client_payload.env }} env
