name: Selective deploy

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  default:
    if: '${{ ! github.event.client_payload.services }}'
    runs-on: ubuntu-latest
    steps:
      - run |
        echo '::set-output name=services::["a-service","b-service","c-service"]'

  build:
    strategy:
      matrix:
        app_name: ${{ github.event.client_payload.services }}

    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.app_name }} done 
