name: Deploy Nightly
on:
  push:
    branches:
      - main
jobs:
  validate:
    name: Validate nightly
    strategy:
      fail-fast: false
      matrix:
        payload:
          - env: DEV
            kube_config_data_secret: DEV_KUBE_CONFIG_DATA
          - env: QA
            kube_config_data_secret: QA_KUBE_CONFIG_DATA
    runs-on: ubuntu-latest
    steps:
      - name: Check ${{ matrix.env }} deployments
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets[matrix.kube_config_data_secret] }}
        with:
          args: wait deployment -lapp --for=condition=Available --timeout=30m
  deploy:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        payload:
          - env: dev
            branch: master
          - env: qa
            branch: qa
    runs-on: ubuntu-latest
    steps:
      - name: Expose token
        id: hasToken
        run: |
          if test -n "${{secrets.TRIGGER_TOKEN}}"; then
            echo '::set-output name=hasToken::true'
          fi
      - name: Trigger ${{ matrix.env }}
        uses: peter-evans/repository-dispatch@v2
        if: steps.hasToken.output.hasToken == 'true'
        with:
          token: ${{ secrets.TRIGGER_TOKEN }}
          repository: ${{ github.repository }}
          event-type: selective-build-and-deploy
          client-payload: |
            {
              "env": "${{ matrix.payload.env }}",
              "branch": "${{ matrix.payload.branch }}"
            }
