name: Selective deploy

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  defaults:
    outputs:
      services: ${{ jobs.defaults.main.services }}
    runs-on: ubuntu-latest
    steps:
      - id: main
        run: |
          if test -n '${{ github.event.client_payload.services }}'; then
            echo '::set-output name=services::${{ github.event.client_payload.services }}'
          else
            echo '::set-output name=services::["a-service","b-service","c-service"]'
          fi
  build:
    needs: defaults
    strategy:
      matrix:
        app_name: ${{ needs.defaults.outputs.services }}

    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.app_name }} done
