name: Deploy Nightly
on:
  push:
    branches:
      - main
jobs:
  validate:
    name: Validate nightly
    strategy:
      fail-fast: false
      matrix:
        payload:
          - env: DEV
            kube_config_data_secret: DEV_KUBE_CONFIG_DATA
          - env: QA
            kube_config_data_secret: QA_KUBE_CONFIG_DATA
    runs-on: self-hosted-back
    steps:
      - name: Check ${{ matrix.env }} deployments
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets[matrix.kube_config_data_secret] }}
        with:
          args: wait deployment -lapp --for=condition=Available --timeout=30m
  trigger:
    strategy:
      fail-fast: false
      matrix:
        payload:
          - env: "dev"
            branch: main
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ${{ matrix.env }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TOKEN }}
          repository: ${{ github.repository }}
          event-type: selective-build-and-deploy
          client-payload: |
            {
              "env": "${{ matrix.payload.env }}",
              "branch": "${{ matrix.payload.branch }}"
            }
