name: Deploy Nightly
on:
  push:
    branches:
      - main
jobs:
  test_1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: |
          echo hi
  test_2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          bye
  trigger:
    strategy:
      fail-fast: false
      matrix:
        payload:
          - env: "dev"
            branch: main
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ${{ matrix.env }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TOKEN }}
          repository: ${{ github.repository }}
          event-type: selective-build-and-deploy
          client-payload: |
            {
              "env": "${{ matrix.payload.env }}",
              "branch": "${{ matrix.payload.branch }}"
            }
