name: Selective deploy

on:
  repository_dispatch:
    types: selective-build-and-deploy

jobs:
  build:
    strategy:
      matrix:
        app_name: ${{ github.event.client_payload.services }}
    runs-on: ubuntu-latest
    steps: |
      echo ${{ matrix.app_name }} done
