name: Deploy Nightly
on:
  push:
    branches:
      - main

jobs:
  trigger:
    strategy:
      fail-fast: false
      matrix:
        env: ["dev", "qa"]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ${{ matrix.env }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TRIGGER_TOKEN }}
          repository: ${{ github.repository }}
          event-type: selective-build-and-deploy
          client-payload: >
            {
              "event_type": "selective-build-and-deploy",
              "client_payload": {
                "env": "${{ matrix.env }}",
                "branch": "${{ matrix.env }}"
              }
            }

